spring:
  application:
    name: demo
  freemarker:
    settings:
      default_encoding: UTF-8
      number_format: 0.######
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_format: HH:mm:ss
    suffix: .ftl
    template-loader-path: classpath:/templates/

server:
  port: 8081
  version: v1.0